spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dailylog?characterEncoding=UTF-8&serverTimezone=UTC 
    username: postgres
    password: 1234

